### ISSUE TITLE
Feature request: dispose function should be passed the time when an entry would have naturally expired

### ISSUE THREAD

**Issue by adevine** [isaacs/ttlcache#12]
I have a use case where I need to know, if an entry is evicted because the cache is full, what time that entry _would_ have naturally expired. Thus, I would like to change the signature of the dispose callback function from:

`dispose(value, key, reason)`

to

`dispose(value, key, reason, expirationTime)`

where expirationTime is the time, in milliseconds since the epoch, when the entry would have naturally expired. Of course, if reason is 'stale' then expirationTime isn't that useful, but if reason is 'set', 'evict' or 'delete' then there are use cases where expirationTime could be valuable.

Right now I can work around this by just setting the value to an object that includes the expiration time, but it would be cleaner/more accurate if I could get the expirationTime directly in the dispose method.

I looked through the source and this should be an easy change. I'm happy to submit a PR for it if you think this feature request is a good idea, but wanted to check with you first. I think this change should be considered backwards compatible as it's just passing an additional parameter to dispose (previously existing dispose functions would just ignore the expirationTime).

Thanks for a great and useful library!

**Comment by adevine** [comment]
FYI, here is the commit on my fork that has these changes: https://github.com/adevine/ttlcache/commit/f2ba2caf8182d499e991223b724e67c9ded0121a

I need to add tests and update the README before submitting a PR, but should be clear on what the request is.

**Comment by isaacs** [comment]
I'm somewhat hesitant to add this, because tacking on yet another argument to the `dispose()` signature is sort of an antipattern.  3 is already pushing it (but I guess `val` and `key` kind of go together.)

Also, what you'll normally get is not really "epoch time", since this module uses node's `performance` builtin, which tracks ns since.... some arbitrary ambiguous time in the past.

To be honest, while "just track this yourself in an object if you care about it" might feel a bit kludgey, I think it is actually the most elegant solution.
