### ISSUE TITLE
Module not found: Can't resolve 'perf_hooks'

### ISSUE THREAD

**Issue by tunguyen-ct** [isaacs/ttlcache#13]
Hi @isaacs, following up https://github.com/isaacs/ttlcache/issues/8#issuecomment-1217194429, this is my minimal setup to reproduce the warning. Thank you so much for your help.

# Step to reproduct

1. Create a fresh Next.js application

```
npx create-next-app@latest --typescript myapp
```

2. Install @isaacs/ttlcache

```
npm install @isaacs/ttlcache
```

3. Edit myapp/pages/_app.tsx

```js
import '../styles/globals.css'
import type { AppProps } from 'next/app'

import TTLCache from '@isaacs/ttlcache'
const cache = new TTLCache({ max: 10000, ttl: 1000 })

function MyApp({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />
}

export default MyApp
```

4. Observe

> warn  - ./node_modules/@isaacs/ttlcache/index.js
Module not found: Can't resolve 'perf_hooks' in '/.../myapp/node_modules/@isaacs/ttlcache'

**Comment by isaacs** [comment]
I'm not super familiar with next, but this looks like you're attempting to bundle some code for the frontend, which has a reference to TTLCache (that is, referencing it via closure from a React component).  The code works, but it looks like the bundler is getting upset because of the `require()`.

Since node exposes `performance` as a global, I'll just use that instead.  It only means that node versions that have the `perf_hooks` module but don't have the `performance` global will use Date instead of performance.

**Comment by tunguyen-ct** [comment]
The warning is gone. Thank you very much.
