### ISSUE TITLE
Too slow

### ISSUE THREAD

**Issue by falsandtru** [isaacs/ttlcache#14]
`for (const exp in this.expirations)` takes over 200ms to get the first entry when 1e6+ entries exist.

**Comment by falsandtru** [comment]
```console
$ node -e 'let o={};for(let i=1e6;i--;)o[i]=0;let t=Date.now();for(const i in o)break;console.log(Date.now()-t);'
249
```

**Comment by isaacs** [comment]
Well, always happy to accept patches that make my code faster, as long as it comes with reasonably representative benchmarks and doesn't negatively impact usability or maintainability.

There's a lot of cache modules out there, if you find that this one doesn't do what you need, probably there's some others that do.

**Comment by falsandtru** [comment]
You don't understand that your library's performance is only ***3-5 ops/sec*** although a heap algorithm is over 1,000,000 ops/sec.

**Comment by isaacs** [comment]
Please share a proof of concept that shows bad behavior of this module. I have not observed what you're describing. It purges  very fast when I have 1e6 entries in it.

**Comment by falsandtru** [comment]
A proof of concept is https://github.com/isaacs/ttlcache/issues/14#issuecomment-1243045663. What is your result of it?

**Comment by falsandtru** [comment]
> It purges very fast when I have 1e6 entries in it.

That is probably because you purged all entries at once in single call of `for (const exp in this.expirations)`.

**Comment by isaacs** [comment]
I mean a proof of concept that uses ttlcache.

On my laptop, using node v18:

```
$ node -e 'let o={};for(let i=1e6;i--;)o[i]=0;for(let i=3;i--;){let t=Date.now();for(const _ in o)break;console.log(Date.now()-t)}'
42
85
69
```

On a tiny Ubuntu droplet using node v12:

```
root@mc:~# node -e 'let o={};for(let i=1e6;i--;)o[i]=0;for(let i=3;i--;){let t=Date.now();for(const _ in o)break;console.log(Date.now()-t)}'
217
193
152
```

The only way I can get something approaching pathological performance from ttl cache itself is by creating a cache with 1e6 entries each having a different TTL, and then advancing the clock manually, but when I dig into it, the poor performance comes from firing all the timers at once, not the purging itself.  It does look like there's some worthwhile perf gains to be had by debouncing those.  Ie, if there's a timer within some number of ms from a new timer being scheduled, cancel the earlier one, since its entries will be purged anyway, so you get better performance (no timers firing every ms) at the expense of _slightly_ lower resolution on expiration purges.  But that's separate from the issue you're pointing at here, which is why I'm asking for a POC that uses TTLCache, so that I can dig into the actual issue.  (And, it is more related to the _frequency_ than the overall size.)

If it comes to it, and I do have to refactor to not rely on an object with integer-string keys for autosorting, then it'll require a data structure that can stay sorted, and this module gets much more complicated.  The goal here is to have something reasonable efficient with low complexity, so implementing a red-black tree or something isn't really ideal.

Another alternative is to remove the ability to specify a ttl in the `set()` call, so that we can guarantee that items are always going to expire out in insertion order, and then it can be a simple queue.  But I know there are people using this to store things with arbitrary TTLs, so that'd also be a pretty significant drawback.  (You could still use a simple array and just assume that it'll _usually_ expire in insertion order, and then branch off only when this constraint doesn't hold, but again, that makes it get kind of complicated.  Splicing into an array is a terrible idea, performance goes completely sideways in surprising ways when you do that.)

So, give me a test using this module that shows bad behavior, and let's see what can be done about it.

**Comment by falsandtru** [comment]
Since calling purgeToCapacity or purgeStale method can be very slow in the case I explained, calling set method with a new unique expiration will also be very slow when max size is limited to 1e6 and 1e6 unique expirations are already registered.
